// Auto-generated by tools/aurora/gen-loopback-tls.mjs — do not edit.
#ifndef AUROBORE_TLS_FINGERPRINT_H
#define AUROBORE_TLS_FINGERPRINT_H

namespace Aurobore {
namespace TlsFingerprint {

static const char kSpkiFingerprintBase64[] = "NopCOsr/hwMV8AheRGDT7ycmEckIGtRCbyhjASee8ho=";

} // namespace TlsFingerprint
} // namespace Aurobore

#endif
