Name:       ru.auroraos.reactdemo
Summary:    React Demo
Version:    1.0.0
Release:    1
License:    MIT
URL:        https://github.com/aurobore/aurobore
Source0:    %{name}-%{version}.tar.bz2

BuildRequires:  cmake
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(auroraapp)
BuildRequires:  pkgconfig(aurorawebview)
BuildRequires:  ru.auroraos.webview-devel

Requires:       ru.auroraos.webview

%description
React Demo — Aurobore application.

%prep
%setup -q

%build
%cmake
%make_build

%install
%make_install

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/172x172/apps/%{name}.png
%{_datadir}/%{name}/translations/*.qm

%changelog
* Wed Jul  1 2026 Aurobore <aurobore@local> - 1.0.0-1
- Generated by aurobore build.
